---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: presync-verifier
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presync-verifier-{{ .Release.Namespace }}
rules:
  - apiGroups: ["kyverno.io"]
    resources: ["clusterpolicies"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: presync-verifier-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: presync-verifier
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: presync-verifier-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
