apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: {{ .Values.lvmCluster.name | default "lvmcluster" }}
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: {{ .Values.lvmCluster.deviceClass | default "vg1" }}
      deviceSelector:
        paths:
        - /dev/nvme1n1
        - /dev/nvme2n1
        - /dev/nvme3n1