global:
  pattern: coco-pattern
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  # This defines whether or not to use upstream resources for CoCo.
  # Defines whether or not the hub cluster can be used for confidential containers
  coco:
    azure:
      enabled: true
      defaultVMFlavour: "Standard_DC2as_v5"

  azure:
    clientID: 'c6a4da9a-ce25-4c39-8c0b-c4fe3bc2087c'
    subscriptionID: 'ce3de9a8-39e2-4cb8-a5cc-369e7043f5f4'
    tenantID: '64dc69e4-d083-49fc-9569-ebece1dd1408'
    DNSResGroup: 'openenv-9sl24'
    hostedZoneName: '9sl24.azure.redhatworkshops.io'
    clusterResGroup: 'coco-rs5j5-rg'
    clusterSubnet: '/subscriptions/ce3de9a8-39e2-4cb8-a5cc-369e7043f5f4/resourceGroups/coco-rs5j5-rg/providers/Microsoft.Network/virtualNetworks/coco-rs5j5-vnet/subnets/coco-rs5j5-worker-subnet'
    clusterNSG: '/subscriptions/ce3de9a8-39e2-4cb8-a5cc-369e7043f5f4/resourceGroups/coco-rs5j5-rg/providers/Microsoft.Network/networkSecurityGroups/coco-rs5j5-nsg'
    clusterRegion: 'westus'

  dscDeployed: false


  objectStorage:
    # Whether or not to use PVC storage
    pvcStorage: true
    replicas: 3
    storagePool: 50Gi
    backingStorageClass: "managed-csi" # push into override file
    # IF ODF exists we don't need to deploy an storage system
    existingODF: false
    odfStorageSystem: "ocs-external-storagecluster-storagesystem"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
