global:
  dscDeployed: true
  pattern: coco-pattern
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  # This defines whether or not to use upstream resources for CoCo.
  # Defines whether or not the hub cluster can be used for confidential containers
  coco:
    azure:
      enabled: true
      defaultVMFlavour: "Standard_DC2as_v5"

  azure:
    clientID: 'f302b3ef-07b2-45f4-8348-774029c3647d'
    subscriptionID: '18e6737a-b665-4e47-85d7-2aca4ce229d8'
    tenantID: 'redhat0.onmicrosoft.com'
    DNSResGroup: 'openenv-r9n2w'
    hostedZoneName: 'r9n2w.azure.redhatworkshops.io'
    clusterResGroup: 'ocp-rcj9f-rg'
    clusterSubnet: '"/subscriptions/18e6737a-b665-4e47-85d7-2aca4ce229d8/resourceGroups/ocp-rcj9f-rg/providers/Microsoft.Network/virtualNetworks/ocp-rcj9f-vnet/subnets/ocp-rcj9f-worker-subnet'
    clusterNSG: '/subscriptions/18e6737a-b665-4e47-85d7-2aca4ce229d8/resourceGroups/ocp-rcj9f-rg/providers/Microsoft.Network/networkSecurityGroups/ocp-rcj9f-nsg'
    clusterRegion: 'southeastasia'




  objectStorage:
    # Whether or not to use PVC storage
    pvcStorage: true
    replicas: 3
    storagePool: 50Gi
    backingStorageClass: "managed-csi" # push into override file
    # IF ODF exists we don't need to deploy an storage system
    existingODF: false
    odfStorageSystem: "ocs-external-storagecluster-storagesystem"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
