global:
  pattern: coco-pattern
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  # This defines whether or not to use upstream resources for CoCo.
  # Defines whether or not the hub cluster can be used for confidential containers
  coco:
    azure:
      enabled: true
      defaultVMFlavour: "Standard_DC2as_v5"

  objectStorage:
    # Whether or not to use PVC storage
    pvcStorage: true
    replicas: 3
    storagePool: 50Gi
    backingStorageClass: "managed-csi"
    # IF ODF exists we don't need to deploy an storage system
    existingODF: false
    odfStorageSystem: "ocs-external-storagecluster-storagesystem"


sandbox:
  azureResGroup: ''
  azureRegion: ''
  azureSubnet: ''
  azureNSG: ''
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
