global:
  cocoUpstream: true
  cocoConverged: true
  azure:
    clusterResGroup: ''
    clusterSubnet: ''
    clusterNSG: ''
    clusterRegion: ''

secretStore:
  name: vault-backend
  kind: ClusterSecretStore



sandbox:
  deploy: true
  sshKey: secret/data/global/sshKey
  azure: true
  peerpodsCreds: secret/data/global/azure
  # These variables today limit to one cluster
  # revise using imperative framework to infer from cluster vars
  # Strongly advised to override in values-global.yaml or values-{cluster-group}.yaml
