{{- if and .Values.sandbox.azure .Values.sandbox.deploy }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: openshift-sandboxed-containers-operator
data:
  CLOUD_PROVIDER: "azure"
  VXLAN_PORT: "9000"
  AZURE_INSTANCE_SIZE: "Standard_DC2as_v5" # CoCo peer pod
  AZURE_INSTANCE_SIZES: "Standard_DC2as_v5,Standard_DC4as_v5,Standard_DC8as_v5,Standard_DC16as_v5"
  AZURE_RESOURCE_GROUP: "{{ .Values.global.azure.clusterResGroup }}"
  AZURE_REGION: "{{ .Values.global.azure.clusterRegion }}"
  AZURE_SUBNET_ID: "{{ .Values.global.azure.clusterSubnet }}" 
  AZURE_NSG_ID: "{{ .Values.global.azure.clusterNSG }}"
  DISABLECVM: "false"
  AZURE_IMAGE_ID: "" # This will get rewritten when the image is built
  AA_KBC_PARAMS: "cc_kbc::https://kbs-trustee-operator-system.{{ .Values.global.hubClusterDomain }}"
  PROXY_TIMEOUT: "5m"
{{- end }}