{{- if .Values.sandbox.azure }}
---
# Separated out to compo
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: peer-pods-cm
#   namespace: openshift-sandboxed-containers-operator
# data:
#   CLOUD_PROVIDER: "azure"
#   VXLAN_PORT: "9000"
#   AZURE_INSTANCE_SIZE: "Standard_DC2as_v5" # CoCo peer pod
#   AZURE_INSTANCE_SIZES: "Standard_DC2as_v5,Standard_DC4as_v5,Standard_DC8as_v5,Standard_DC16as_v5"
#   AZURE_RESOURCE_GROUP: "{{ .Values.sandbox.azureResGroup }}"
#   AZURE_REGION: "{{ .Values.sandbox.azureRegion }}"
#   AZURE_SUBNET_ID: "{{ .Values.sandbox.azureSubnet }}" 
#   AZURE_NSG_ID: "{{ .Values.sandbox.azureNSG }}"
#   DISABLECVM: "false"
#   AZURE_IMAGE_ID: "" # Note 
#   #AA_KBC_PARAMS: "cc_kbc::https://kbs-service-kbs-operator-system.{{ .Values.global.hubClusterDomain }}"
#   AA_KBC_PARAMS: "cc_kbc::http://kbs-service.trustee-operator-system.svc.cluster.local:8080"
#   PROXY_TIMEOUT: "5m"
{{- end }}