apiVersion: v1
data:
{{ if eq .Values.baremetal.cpu "amd" }}
  osImageURL: "quay.io/openshift_sandboxed_containers/rhcos-layer/ocp-4.18:snp-0.2.1"
  {{- else }}
  osImageURL: "quay.io/openshift_sandboxed_containers/rhcos-layer/ocp-4.18:tdx-0.2.1"
  kernelArguments: "kvm_intel.tdx=1"
  {{- end }}
kind: ConfigMap
metadata:
  name: layered-image-deploy-cm
  namespace: openshift-sandboxed-containers-operator