apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-dcap-registration-flow
  namespace: intel-dcap
spec:
  selector:
    matchLabels:
      name: intel-dcap-registration-flow
  template:
    metadata:
      labels:
        name: intel-dcap-registration-flow
    spec:
      serviceAccountName: intel-dcap-registration-flow
      nodeSelector:
        intel.feature.node.kubernetes.io/sgx: 'true'
      containers:
      - name: intel-dcap-registration-flow
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: true
          privileged: true # Required to access host efivarfs
        volumeMounts:
          - name: efivars
            mountPath: /sys/firmware/efi/efivars
        workingDir: "/opt/intel/sgx-pck-id-retrieval-tool/"
        image: quay.io/openshift_sandboxed_containers/dcap/dcap-registration-flow:0.2.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: pccs-registration
      volumes:
        - name: efivars
          hostPath:
            path: /sys/firmware/efi/efivars/