

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-cluster-admin
subjects:
{{- range .Values.clusterAdmins }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io