apiVersion: v1
kind: ServiceAccount
metadata:
  name: kbs-access-curl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kbs-access-curl-privileged-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: kbs-access-curl
    namespace: {{ .Release.Namespace }}
