# Chart-specific values
# Common values are inherited from values-global.yaml

defaultMemory: ""

runtimeClassName: ""
global:
  clusterPlatform: ""  # Cluster platform: "Azure", "AWS", etc. - determines runtime class
