apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: {{ .Values.kbs.deployNS }}
data:
  policy.rego: |
    package policy
    import rego.v1
    default allow = false
    allow if {
      input["submods"]["cpu"]["ear.status"] != "contraindicated"
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["configuration"] == 2
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["hardware"] == 2
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["executables"] == 3
    }
