apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-policy-web-content
  labels:
    app: insecure-policy
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello OpenShift</title>
    </head>
    <body>
        <h1>Hello, OpenShift!</h1>
        <p>This confidential container is running with an insecure (debug) policy on Red Hat httpd.</p>
    </body>
    </html>
