apiVersion: v1
kind: Service
metadata:
  name: insecure-policy
spec:
  ports:
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: insecure-policy
  sessionAffinity: None
  type: ClusterIP
