apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: insecure-policy
spec:
  port:
    targetPort: 8888-tcp
  to:
    kind: Service
    name: insecure-policy
    weight: 100
  wildcardPolicy: None
