apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-web-content
  labels:
    app: secure
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello OpenShift</title>
    </head>
    <body>
        <h1>Hello, OpenShift!</h1>
        <p>This confidential container is running on Red Hat httpd.</p>
    </body>
    </html>
