apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard
  labels:
    app: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standard
  template:
    metadata:
      labels:
        app: standard
    spec:
      containers:
        - name: hello-openshift
          image: registry.redhat.io/ubi9/httpd-24@sha256:68a91ff691092f455fea682330c499588747231c16516cd4f35aff821e6847f2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: web-content
              mountPath: /var/www/html
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: web-content
          configMap:
            name: standard-web-content
