#!/usr/bin/env bash
set -euo pipefail

# Generate trustee chart overrides and values-secret entries for SNP VCEK certs.
# Requires: ~/.coco-pattern/snp-vcek/<hwid>/vcek.der from download step.
# Output: overrides/values-snp-vcek.yaml (chart values)
#         stdout: values-secret.yaml entries to add

VCEKDIR="${HOME}/.coco-pattern/snp-vcek"
OVERRIDE_FILE="overrides/values-snp-vcek.yaml"

HWIDS=()
for DIR in "${VCEKDIR}"/*/; do
  [ -d "${DIR}" ] || continue
  HWID=$(basename "${DIR}")
  [ "${HWID}" = "*" ] && continue
  if [ -f "${DIR}/vcek.der" ]; then
    HWIDS+=("${HWID}")
  fi
done

if [ ${#HWIDS[@]} -eq 0 ]; then
  echo "ERROR: no VCEK certificates found in ${VCEKDIR}/<hwid>/vcek.der"
  echo "Run 'make snp-download-vcek' first."
  exit 1
fi

echo "Found ${#HWIDS[@]} VCEK certificate(s)."
echo ""

# Generate overrides/values-snp-vcek.yaml
mkdir -p overrides
cat > "${OVERRIDE_FILE}" <<'HEADER'
# Generated by: make snp-gen-overrides
# AMD SEV-SNP VCEK certificate configuration for offline attestation.
# Do not edit manually — re-run the generator if nodes change.
kbs:
  snp:
    enabled: true
    vcekSecrets:
HEADER

for HWID in "${HWIDS[@]}"; do
  SHORT="${HWID:0:12}"
  echo "    - hwid: \"${HWID}\"" >> "${OVERRIDE_FILE}"
  echo "      secretName: \"snp-vcek-${SHORT}\"" >> "${OVERRIDE_FILE}"
done

echo "Generated: ${OVERRIDE_FILE}"
echo ""

# Print values-secret.yaml entries
echo "================================================================"
echo "Add the following to your values-secret.yaml (under secrets:):"
echo "================================================================"
echo ""

for HWID in "${HWIDS[@]}"; do
  SHORT="${HWID:0:12}"
  cat <<EOF
  - name: snpVcek-${HWID}
    vaultPrefixes:
    - hub
    fields:
    # base64: true is required because vcek.der is a binary DER certificate.
    # Vault KV-v2 stores JSON (UTF-8 strings only); the VP base64 flag encodes
    # binary before the Vault write. ESO decodingStrategy: Base64 decodes on read.
    - name: vcek.der
      path: ~/.coco-pattern/snp-vcek/${HWID}/vcek.der
      base64: true

EOF
done

echo "================================================================"
echo ""
echo "After adding the entries above, run: make load-secrets"
