---
apiVersion: v1
kind: Secret
metadata:
  name: 
data:
  # Base64 encoding of install-config yaml
  secret: "sealed.fakejwsheader.{{ tpl  "sealed-secret.json" .  | base64 }}.fakesignature"
type: Opaque