---
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secret

data:
  # Base64 encoding of install-config yaml
  secret: "{{ printf "sealed.fakejwsheader.%s.fakesignature" (tpl ( .Files.Get "sealed-secret.json" ) . | b64enc ) | b64enc }}"
type: Generic