---
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secret
data:
  # Base64 encoding of install-config yaml
  secret: '{{ "sealed.fakejwsheader."{{ tpl  "sealed-secret.json" .  | b64enc }}".fakesignature" | b64enc }}'
type: Generic