global:
  cocoUpstream: true
  cocoConverged: true
  azure:
    clusterResGroup: ''
    clusterSubnet: ''
    clusterNSG: ''
    clusterRegion: ''

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

sandbox:
  deploy: true
  sshKey: secret/data/global/sshKey
  azure: true
  # Peer pod image defined, if required to avoid rebuilds.
  peerPodImage: ""
  # image below is not available in eastasia
  #peerPodImage: '/CommunityGalleries/cococommunity-42d8482d-92cd-415b-b332-7648bd978eff/Images/peerpod-podvm-fedora-debug/Versions/0.12.0'
  # These variables today limit to one cluster
  # revise using imperative framework to infer from cluster vars
  # Strongly advised to override in values-global.yaml or values-{cluster-group}.yaml
