apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbs-access-sealed
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kbs-access-sealed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbs-access-sealed
  template:
    metadata:
      labels:
        app: kbs-access-sealed
      annotations:
        coco.io/initdata-configmap: initdata
    spec:
      runtimeClassName: {{ .Values.global.coco.runtimeClassName }}
      containers:
      - name: httpd
        image: registry.redhat.io/ubi9/httpd-24@sha256:68a91ff691092f455fea682330c499588747231c16516cd4f35aff821e6847f2
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: secret-data
          mountPath: /var/www/html
          readOnly: true
        - name: initdata
          mountPath: /opt/confidential-containers/initdata
          readOnly: true
        resources:
          limits:
            memory: "2304Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: secret-data
        secret:
          secretName: kbs-sealed-secret
      - name: initdata
        configMap:
          name: initdata
          optional: false
