apiVersion: v1
kind: Service
metadata:
  name: kbs-access-sealed
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: kbs-access-sealed
spec:
  selector:
    app: kbs-access-sealed
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
