---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: pccs-tls-eso
  namespace: intel-dcap
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pccs-tls
    template:
      type: Opaque
  data:
    - secretKey: private.pem
      remoteRef:
        key: 'secret/data/hub/pccs-tls'
        property: private_key
    - secretKey: file.crt
      remoteRef:
        key: 'secret/data/hub/pccs-tls'
        property: certificate
