---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: pccs-secrets-eso
  namespace: intel-dcap
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pccs-secrets
    template:
      type: Opaque
      data:
        PCCS_API_KEY: "{{ "{{ .api_key }}" }}"
        PCCS_USER_TOKEN_HASH: "{{ "{{ .user_token_hash }}" }}"
        USER_TOKEN: "{{ "{{ .user_token }}" }}"
        PCCS_ADMIN_TOKEN_HASH: "{{ "{{ .admin_token_hash }}" }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: 'secret/data/hub/pccs'
        property: api_key
    - secretKey: user_token_hash
      remoteRef:
        key: 'secret/data/hub/pccs'
        property: user_token_hash
    - secretKey: user_token
      remoteRef:
        key: 'secret/data/hub/pccs'
        property: user_token
    - secretKey: admin_token_hash
      remoteRef:
        key: 'secret/data/hub/pccs'
        property: admin_token_hash
